# en
hp = 'HP'
mp = 'MP'
attack_stat = '    Attack'
defense_stat = ' Defense'
base = 'Base'
plain = 'Plain'
desert = 'Desert'
snow = 'Snow'
forest = 'Forest'
mountain = 'Mountain'
volcano = 'Volcano'

attack = '    Attack'
magic = '    Magic'
inventory = ' Inventory'
leave = '    Leave'

resume = 'RESUME'
settings = 'SETTINGS'
save = 'SAVE'
quit_game = 'QUIT'
