# en
hp = 'HP'
mp = 'MP'
attack_stat = '    Attack'
defense_stat = ' Defense'
base = 'Base'
plain = 'Plain'
desert = 'Desert'
snow = 'Snow'
forest = 'Forest'
mountain = 'Mountain'
volcano = 'Volcano'

attack = '    Attack'
magic = '    Magic'
inventory = ' Inventory'
leave = '    Leave'
back = 'Back'
attack_1 = 'Attack 1'
attack_2 = 'Attack 2'
attack_3 = 'Attack 3'
attack_4 = 'Attack 4'
magic_1 = 'Spell 1'
magic_2 = 'Spell 2'
magic_3 = 'Spell 3'
magic_4 = 'Spell 4'

resume = 'RESUME'
settings = 'SETTINGS'
save = 'SAVE'
quit_game = 'QUIT'
