# fr
attack_stat = '  Attaque'
defense_stat = ' Défense'
base = 'Base'
plain = 'Plaine'
desert = 'Désert'
snow = 'Neige'
forest = 'Forêt'
mountain = 'Montagne'
volcano = 'Volcan'

attack = '   Attaque'
magic = '    Magie'
inventory = ' Inventaire'
leave = '  Abandon'

resume = 'REPRENDRE'
settings = 'PARAMETRES'
save = 'SAUVEGARDER'
quit_game = 'QUITTER'
