# fr
hp = 'PV'
mp = 'PM'
attack_stat = '  Attaque'
defense_stat = ' Défense'
base = 'Base'
plain = 'Plaine'
desert = 'Désert'
snow = 'Neige'
forest = 'Forêt'
mountain = 'Montagne'
volcano = 'Volcan'

attack = '   Attaque'
magic = '    Magie'
inventory = ' Inventaire'
leave = '  Abandon'
back = 'Retour'
attack_1 = 'Attaque 1'
attack_2 = 'Attaque 2'
attack_3 = 'Attaque 3'
attack_4 = 'Attaque 4'
magic_1='Sort 1'
magic_2='Sort 2'
magic_3='Sort 3'
magic_4='Sort 4'

resume = 'REPRENDRE'
settings = 'PARAMETRES'
save = 'SAUVEGARDER'
quit_game = 'QUITTER'
