# fr
hp = 'PV'
mp = 'PM'
attack_stat = 'Attaque'
defense_stat = 'Défense'
base = 'Base'
plain = 'Plaine'
desert = 'Désert'
snow = 'Neige'
forest = 'Forêt'
mountain = 'Montagne'
volcano = 'Volcan'

attack = 'Attaque'
magic = 'Magie'
inventory = 'Inventaire'
leave = 'Abandon'
back = 'Retour'
attack_1 = 'Attaque 1'
attack_2 = 'Attaque 2'
attack_3 = 'Attaque 3'
attack_4 = 'Attaque 4'
magic_1 = 'Soin'
magic_2 = 'Bouclier'
magic_3 = 'Boost Déf.'
magic_4 = 'Boost Att.'
confirm = 'Confirmer'
use = 'Utiliser'
quantity = 'Quantité'

resume = 'REPRENDRE'
settings = 'PARAMETRES'
save = 'SAUVEGARDER'
quit_game = 'QUITTER'
